# This is the authoritative, executable record of every ABI-relevant input for
# the qualified native build. Build guards read this file; update it only via
# the upgrade procedure in native/README.md.
# covers: simd_json.package.native_build_tooling simd_json.native_build_and_abi.pinned_toolchain simd_json.native_build_and_abi.target_qualification simd_json.native_build_and_abi.clean_checkout_build
[
  schema_version: 1,
  qualified_on: ~D[2026-08-29],
  beam: [
    elixir_requirement: "~> 1.18.4",
    qualified_elixir: "1.18.4",
    qualified_otp: "27.3"
  ],
  zigler: [
    version: "0.16.0",
    requirement: "== 0.16.0",
    hex_url: "https://hex.pm/packages/zigler/0.16.0",
    hex_sha256: "867ce49289568a7fabff400cb9f1636a429defcd488f3302a82c4b51b2bc7741",
    threaded_docs: "https://hexdocs.pm/zigler/0.16.0/07-concurrency.html#threaded"
  ],
  zig: [
    version: "0.16.0",
    download_index: "https://ziglang.org/download/index.json",
    primary_archive_url: "https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz",
    primary_archive_sha256: "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00"
  ],
  cxx: [
    driver: "zig c++",
    family: "Zig-bundled Clang/LLVM",
    qualified_version: "21.1.0",
    language_standard: "c++17",
    standard_library: "Zig-bundled libc++",
    linkage: "linked into the NIF by Zig",
    profiles: [
      development: [
        "Zig Debug",
        "-std=c++17",
        "-DSIMDJSON_AVX512_ALLOWED=0",
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden"
      ],
      release: [
        "Zig ReleaseSafe",
        "-std=c++17",
        "-DSIMDJSON_AVX512_ALLOWED=0",
        "-DNDEBUG",
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden"
      ],
      sanitizer: [
        "Zig Debug",
        "-std=c++17",
        "-DSIMDJSON_AVX512_ALLOWED=0",
        "-fno-omit-frame-pointer",
        "-fsanitize=address,undefined",
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden"
      ]
    ]
  ],
  simdjson: [
    version: "4.6.9",
    tag: "v4.6.9",
    commit: "0a2e33f345f49cb6e24401d5b16dbdbc9650921a",
    release_url: "https://github.com/simdjson/simdjson/releases/tag/v4.6.9",
    archive_url: "https://github.com/simdjson/simdjson/releases/download/v4.6.9/singleheader.zip",
    archive_sha256: "d406c794beece1ce6b9f9458914346560686c44a407f7e621299437bf38644ec",
    vendor_directory: "native/vendor/simdjson",
    patch_series: "native/vendor/simdjson/patches/series",
    archive_members: ["simdjson.cpp", "simdjson.h"],
    vendor_files: [
      {"simdjson.cpp", "452f682d543d3476808b25b8d8df8d884f7b7f4b2fb5df51e5123fd03f1c5e00"},
      {"simdjson.h", "0043db870ceb4c19756519ce9b8b8277ca1585d6222c39b9c022271b69884c4b"},
      {"LICENSE", "5fa8894e890bd77958f93b165433e0fb0dffa5bc982bfb147e4748e95bad24e5"},
      {"LICENSE-MIT", "9ed0a34979f22fc33fc13d942233f22d44906c236d876bd05fadf18cb5abf7da"}
    ],
    padding_bytes: 64,
    maximum_document_depth: 1024,
    input_alignment_bytes: 64,
    language_standard: "c++17",
    supported_compilers: ["Clang 6 or newer", "GCC 7 or newer", "MSVC 2017 or newer"],
    expected_x86_64_runtime_dispatch: ["haswell", "westmere", "fallback"],
    license: "Apache-2.0",
    license_files: ["LICENSE", "LICENSE-MIT"]
  ],
  primary_target: [
    triple: "x86_64-linux-gnu",
    operating_system: "Ubuntu 24.04 LTS",
    architecture: "x86_64",
    libc: "glibc 2.39",
    cxx_runtime: "Zig 0.16.0 bundled libc++ linked into the NIF",
    minimum_otp: "27.3",
    minimum_elixir: "1.18.4",
    expected_simdjson_implementations: ["haswell", "westmere", "fallback"]
  ],
  unsupported_target_diagnostic:
    "unsupported native target %{target}; see native/README.md#target-and-cpu-dispatch-matrix",
  cache_inputs: [
    ".tool-versions",
    "mix.exs",
    "mix.lock",
    "lib/simd_json/application.ex",
    "lib/simd_json/native/build_guard.ex",
    "lib/simd_json/native/build_smoke.ex",
    "lib/simd_json/native/operation_coordinator.ex",
    "lib/simd_json/native/pool_options.ex",
    "lib/simd_json/native/projection_operation.ex",
    "lib/simd_json/native/threaded_operation.ex",
    "native/manifest.exs",
    "native/include/simd_json_abi.h",
    "native/include/simd_json_build_smoke.h",
    "native/include/simd_json_nif_internal.h",
    "native/src/build_smoke.cpp",
    "native/src/simd_json_abi.cpp",
    "native/src/simd_json_projection.cpp",
    "native/src/simd_json_stream_cursor.cpp",
    "native/src/simd_json_native_internal.hpp",
    "native/test/document_resource_test.zig",
    "native/test/projection_engine_conformance.c",
    "native/test/projection_plan_test.zig",
    "native/test/stream_cursor_test.zig",
    "native/test/include/simd_json_test_hooks.h",
    "native/symbols/c_abi.allowlist",
    "native/symbols/c_abi.version",
    "native/symbols/nif.allowlist",
    "native/zig/build_smoke.zig",
    "native/zig/worker_pool.zig",
    "native/zig/document_resource.zig",
    "native/zig/projection_plan.zig",
    "native/zig/stream_cursor.zig",
    "native/vendor/simdjson/simdjson.cpp",
    "native/vendor/simdjson/simdjson.h",
    "native/vendor/simdjson/LICENSE",
    "native/vendor/simdjson/LICENSE-MIT",
    "native/vendor/simdjson/patches/series"
  ],
  qualification_inputs: [
    ".tool-versions",
    ".github/workflows/ci.yml",
    ".spec/decisions/0001-native-stack-and-c-abi.md",
    ".spec/decisions/0002-document-resource-and-buffer-ownership.md",
    ".spec/decisions/0003-off-scheduler-native-execution.md",
    ".spec/decisions/0004-projection-api-and-validation-contract.md",
    ".spec/decisions/0005-prefix-sharing-native-projection-engine.md",
    ".spec/decisions/0006-projection-admission-consumption-and-lifetime.md",
    ".spec/decisions/0007-lazy-stream-api-and-bounded-options.md",
    ".spec/decisions/0008-forward-only-batched-array-cursor.md",
    ".spec/decisions/0009-stream-ownership-backpressure-and-lifetime.md",
    ".spec/decisions/0010-bounded-native-pool-configuration-and-admission.md",
    ".spec/decisions/0011-fixed-native-worker-lifecycle.md",
    ".spec/decisions/0012-owned-native-jobs-and-bounded-fifo.md",
    ".spec/decisions/0013-monitored-delivery-and-resource-serialization.md",
    ".spec/planning/milestone_02_projection_api/README.md",
    ".spec/planning/milestone_02_projection_api/phase-01-projection-contract-and-preflight-validation.md",
    ".spec/planning/milestone_02_projection_api/phase-02-abi-v2-and-native-projection-plan.md",
    ".spec/planning/milestone_02_projection_api/phase-03-single-pass-traversal-and-typed-results.md",
    ".spec/planning/milestone_02_projection_api/phase-04-threaded-projection-and-document-consumption.md",
    ".spec/planning/milestone_02_projection_api/phase-05-public-select-api-and-stable-errors.md",
    ".spec/planning/milestone_02_projection_api/phase-06-qualification-benchmarks-and-activation.md",
    ".spec/planning/milestone_03_batched_array_streaming/README.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-01-stream-contract-and-preflight-options.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-02-abi-v3-and-cursor-ownership.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-03-forward-only-array-traversal-and-native-batches.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-04-threaded-stream-lifecycle-and-backpressure.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-05-public-enumerable-and-stable-errors.md",
    ".spec/planning/milestone_03_batched_array_streaming/phase-06-qualification-etl-benchmarks-and-activation.md",
    ".spec/planning/milestone_04_worker_pool/README.md",
    ".spec/planning/milestone_04_worker_pool/phase-01-configuration-and-admission-contract.md",
    ".spec/planning/milestone_04_worker_pool/phase-02-native-pool-state-and-fixed-workers.md",
    ".spec/planning/milestone_04_worker_pool/phase-03-owned-jobs-and-nonblocking-queue.md",
    ".spec/planning/milestone_04_worker_pool/phase-04-cancellation-delivery-and-resource-serialization.md",
    ".spec/research/jason_parser_architecture_analysis.md",
    ".spec/research/milestone_2_projection_runtime_qualification.md",
    ".spec/research/phase_4_scheduler_qualification.md",
    ".spec/research/phase_6_scheduler_qualification.md",
    ".spec/research/simdjson_beam_nif_architecture.md",
    ".spec/research/zigler_0_16_threaded_qualification.md",
    ".spec/specs/document_api.spec.md",
    ".spec/specs/document_resource.spec.md",
    ".spec/specs/native_build_and_abi.spec.md",
    ".spec/specs/native_execution.spec.md",
    ".spec/specs/native_pool.spec.md",
    ".spec/specs/package.spec.md",
    ".spec/specs/projection_api.spec.md",
    ".spec/specs/projection_engine.spec.md",
    ".spec/specs/projection_execution.spec.md",
    ".spec/specs/stream_cursor.spec.md",
    ".spec/specs/stream_execution.spec.md",
    ".spec/specs/streaming_api.spec.md",
    "mix.exs",
    "mix.lock",
    "README.md",
    "docs/milestones/README.md",
    "docs/milestones/01-native-foundation.md",
    "docs/milestones/01-native-foundation-operations.md",
    "docs/milestones/01-native-foundation-acceptance.md",
    "docs/milestones/02-projection-api.md",
    "docs/milestones/02-projection-api-operations.md",
    "docs/milestones/02-projection-api-acceptance.md",
    "docs/milestones/03-batched-array-streaming.md",
    "docs/milestones/03-batched-array-streaming-operations.md",
    "docs/milestones/03-batched-array-streaming-acceptance.md",
    "docs/milestones/04-worker-pool-and-operations.md",
    "bench/stream_etl_policy.exs",
    "bench/stream_fixtures/manifest.exs",
    "bench/stream_fixtures/small.json.gz",
    "bench/stream_fixtures/medium.json.gz",
    "bench/stream_fixtures/million.json.gz",
    "bench/stream_fixtures/huge-row.json.gz",
    "bench/fixtures/manifest.json",
    "bench/fixtures/small.json",
    "bench/fixtures/medium.json",
    "bench/fixtures/large.json",
    "bench/sparse_projection_policy.exs",
    "lib/mix/tasks/simd_json.verify_qualification.ex",
    "lib/mix/tasks/simd_json.verify_traceability.ex",
    "lib/mix/tasks/simd_json.verify_vendor.ex",
    "lib/simd_json.ex",
    "lib/simd_json/application.ex",
    "lib/simd_json/document.ex",
    "lib/simd_json/error.ex",
    "lib/simd_json/projection.ex",
    "lib/simd_json/stream.ex",
    "lib/simd_json/stream_options.ex",
    "lib/simd_json/native/build_guard.ex",
    "lib/simd_json/native/build_smoke.ex",
    "lib/simd_json/native/diagnostics.ex",
    "lib/simd_json/native/operation_coordinator.ex",
    "lib/simd_json/native/pool_options.ex",
    "lib/simd_json/native/projection_operation.ex",
    "lib/simd_json/native/threaded_operation.ex",
    "native/manifest.exs",
    "native/README.md",
    "native/include/simd_json_abi.h",
    "native/include/simd_json_build_smoke.h",
    "native/include/simd_json_nif_internal.h",
    "native/src/build_smoke.cpp",
    "native/src/simd_json_abi.cpp",
    "native/src/simd_json_projection.cpp",
    "native/src/simd_json_stream_cursor.cpp",
    "native/src/simd_json_native_internal.hpp",
    "native/symbols/c_abi.allowlist",
    "native/symbols/c_abi.version",
    "native/symbols/nif.allowlist",
    "native/test/c_abi_conformance.c",
    "native/test/c_abi_header_conformance.c",
    "native/test/document_resource_test.zig",
    "native/test/projection_engine_conformance.c",
    "native/test/projection_plan_conformance.c",
    "native/test/projection_plan_test.zig",
    "native/test/stream_cursor_conformance.c",
    "native/test/stream_cursor_test.zig",
    "native/test/include/simd_json_test_hooks.h",
    "native/vendor/simdjson/simdjson.cpp",
    "native/vendor/simdjson/simdjson.h",
    "native/vendor/simdjson/LICENSE",
    "native/vendor/simdjson/LICENSE-MIT",
    "native/vendor/simdjson/patches/series",
    "native/zig/build_smoke.zig",
    "native/zig/document_resource.zig",
    "native/zig/projection_plan.zig",
    "native/zig/stream_cursor.zig",
    "scripts/ci/qualify_native_release.sh",
    "scripts/ci/qualify_milestone_1.sh",
    "scripts/ci/qualify_document_api.sh",
    "scripts/ci/qualify_document_resource.sh",
    "scripts/ci/qualify_runtime.sh",
    "scripts/ci/qualify_projection_benchmark.sh",
    "scripts/ci/qualify_projection_execution.sh",
    "scripts/ci/qualify_projection_runtime.sh",
    "scripts/ci/qualify_stream_runtime.sh",
    "scripts/ci/qualify_stream_benchmark.sh",
    "scripts/ci/qualify_stream_execution.sh",
    "scripts/ci/qualify_milestone_2.sh",
    "scripts/ci/qualify_milestone_3.sh",
    "scripts/ci/verify_milestone_1_scope.sh",
    "scripts/ci/verify_offline_native_build.sh",
    "scripts/native/run_c_abi_conformance.sh",
    "scripts/native/run_nif_sanitizer_tests.sh",
    "scripts/native/run_zig_resource_tests.sh",
    "scripts/native/verify_release_symbols.sh",
    "scripts/benchmarks/generate_sparse_fixtures.exs",
    "scripts/benchmarks/run_sparse_projection.exs",
    "scripts/benchmarks/generate_stream_fixtures.exs",
    "scripts/benchmarks/run_stream_etl.exs",
    "test/benchmark/sparse_fixture_test.exs",
    "test/native/build_guard_test.exs",
    "test/native/build_smoke_test.exs",
    "test/native/c_abi_conformance_test.exs",
    "test/native/c_abi_header_test.exs",
    "test/native/document_resource_policy_test.exs",
    "test/native/document_resource_registration_test.exs",
    "test/native/native_build_policy_test.exs",
    "test/native/native_execution_integration_test.exs",
    "test/native/pool_options_test.exs",
    "test/native/pool_cancellation_test.exs",
    "test/native/pool_delivery_test.exs",
    "test/native/pool_queue_test.exs",
    "test/native/pool_resource_serialization_test.exs",
    "test/native/pool_worker_lifecycle_test.exs",
    "test/native/projection_binary_lifetime_test.exs",
    "test/native/projection_document_lifecycle_test.exs",
    "test/native/release_symbol_test.exs",
    "test/native/stream_cursor_resource_test.exs",
    "test/native/stream_document_lifecycle_test.exs",
    "test/native/threaded_stream_lifecycle_test.exs",
    "test/native/threaded_admission_test.exs",
    "test/native/threaded_document_open_test.exs",
    "test/native/threaded_projection_integration_test.exs",
    "test/native/threaded_projection_operation_test.exs",
    "test/native/threaded_teardown_test.exs",
    "test/native/zig_resource_test.exs",
    "test/qualification/lifecycle_memory_qualification_test.exs",
    "test/qualification/native_release_qualification_test.exs",
    "test/qualification/projection_lifecycle_qualification_test.exs",
    "test/qualification/projection_scheduler_qualification_test.exs",
    "test/qualification/scheduler_qualification_test.exs",
    "test/qualification/stream_runtime_qualification_test.exs",
    "test/simd_json/document_api_test.exs",
    "test/simd_json/error_test.exs",
    "test/simd_json/phase_5_integration_test.exs",
    "test/simd_json/projection_validation_test.exs",
    "test/simd_json/public_surface_test.exs",
    "test/simd_json/select_test.exs",
    "test/simd_json_test.exs",
    "test/simd_json/stream_options_test.exs",
    "test/simd_json/stream_constructor_test.exs",
    "test/simd_json/stream_enumerable_test.exs",
    "test/test_helper.exs",
    ".spec/research/phase_6_scheduler_qualification.md"
  ]
]
